version: "3.8"
services:
  front:
    container_name: nextjs
    image: nodejs-docker:1.0.0
    build:
      context: .
      target: dev
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - node_modules:/app/node_modules
      - .:/app:delegated
volumes:
  node_modules: {}
